---
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
    - vars/vars-homebrew.yml
    - vars/vars-dotfiles.yml
    - vars/vars-dockutil.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles
    - fubarhouse.macfonts
    - fubarhouse.macdock

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/preferences.yml
