---
# Sudoers configuration (enables more convenient Vagrant usage).
- name: Copy sudoers configuration into place.
  become: yes
  become_user: root
  copy:
    src: files/etc/sudoers
    dest: /etc/sudoers
    mode: 0440
    validate: 'visudo -cf %s'
  when: configure_sudoers
  ignore_errors: yes
